build:
	$(info *** O comando make / make build cria o executável 'server'. ***)
	$(info ***   execute da forma: ./server   ***)
	$(info ***   O server utilizará a porta 50051 - O client já está configurado com essa porta  ***)
	go build -o server server.go

all:
	build

run:
	./server
